### ISSUE TITLE
Consumes 76% of CPU for hours at a time

### ISSUE THREAD

**Issue by parkr** [sstephenson/launch_socket_server#2]
Hey @sstephenson! I have an interesting one for you.

I will often have to kill the `launch_socket_server` process after the fans on my workstation start going crazy. Is there a possibility of a very large loop or otherwise very CPU-intensive process that could stall at 76% of CPU for a long time? Memory usage remains very low during these prolonged CPU spikes.

I haven't debugged a live Go process before, but if that's a thing, I'd be happy to give that a try next time. Usually happens twice a day, and has been happening for a few weeks.

**Comment by parkr** [comment]
@sstephenson, more info for you. Every 8 seconds, I see this:

``` text
launch_socket_server: error accepting connection: accept tcp 0.0.0.0:0: accept: invalid argument
```

Could this be an issue with macOS Sierra? I am running macOS Sierra.

**Comment by parkr** [comment]
I took a `/usr/bin/sample` of it: https://gist.github.com/parkr/490fe59baf0d3af76cac8f3cbe64847d

**Comment by maddox** [comment]
I see this all the time now too. I actually came here looking to see if this had been filed yet and found this.

**Comment by kdaigle** [comment]
Another report here, same problem. Ended up force killing it. Happy to provide debugging information if something would help.

**Comment by mistydemeo** [comment]
Encountered a few more people running into this problem; haven't yet figured out a solution beyond killing the service and restarting.
